# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_width', models.CharField(max_length=5)),
                ('prod_artno', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=500)),
                ('prod_rps', models.FloatField(default=0)),
                ('prod_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=500)),
                ('subcat_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Category')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='prod_subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Subcat'),
        ),
    ]
